import type { InvoiceData } from "@/lib/pdf/invoice-pdf";
import { DEFAULT_PRINT_SETTINGS } from "@/lib/settings/companySettings";

/** Sample invoice used by the Print Settings live preview. Bangla-safe. */
export const SAMPLE_INVOICE: InvoiceData = {
  type: "invoice",
  title: "TAX INVOICE",
  company: {
    name: "এরপোভো ট্রেডিং",
    business_type: "Retail & Wholesale",
    address: "১২৩ গুলশান অ্যাভিনিউ, ঢাকা ১২১২",
    phone: "+880 1700-000000",
    email: "hello@erpovo.example",
    gst_number: "BIN 123456789-0102",
    logo_url: null,
    signature_url: null,
  },
  party: {
    name: "করিম এন্টারপ্রাইজ",
    phone: "+880 1900-111111",
    address: "৪৫ ধানমন্ডি ৩২, ঢাকা",
    gst_number: "BIN 987654321-0202",
  },
  number: "INV-2026-0042",
  date: "03 Jun 2026",
  dueDate: "17 Jun 2026",
  paymentMethod: "Bank Transfer",
  lines: [
    {
      name: "বাসমতি চাল (প্রিমিয়াম)",
      description: "১ কেজি প্যাক · ব্যাচ #B204",
      qty: 25,
      unit: "KG",
      price: 180,
      discount_pct: 5,
      tax_pct: 5,
      amount: 4275,
    },
    {
      name: "সরিষার তেল",
      qty: 10,
      unit: "LTR",
      price: 320,
      discount_pct: 0,
      tax_pct: 5,
      amount: 3200,
    },
    {
      name: "Marketing Service — June",
      description: "Social media campaign",
      qty: 1,
      unit: "PCS",
      price: 12000,
      tax_pct: 15,
      amount: 12000,
    },
  ],
  subtotal: 19475,
  discount: 225,
  tax: 1862.5,
  deliveryCharge: 150,
  total: 21262.5,
  paid: 10000,
  balance: 11262.5,
  currency: "BDT",
  currencySymbol: "Tk",
  terms: "Goods once sold will not be taken back. Payment due within 15 days.",
  notes: "Thank you for your business!",
  printSettings: { ...DEFAULT_PRINT_SETTINGS },
  signatureLabel: "Authorized Signature",
  footerNote: null,
};
